# Generated by Django 4.1.7 on 2023-03-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='parent_tweet',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweets',
            field=models.IntegerField(default=0),
        ),
    ]
