# Generated by Django 4.1.7 on 2023-03-12 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0002_alter_tweet_likes_alter_tweet_parent_tweet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='likes_users',
            field=models.ManyToManyField(related_name='likes_tweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
